### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by NadiaGarcia6** [GFW-knocker/gfw_resist_http_proxy#1]
Hi,

First of all thank you for all your effort.
Do you have any plans to support SSL in your proxy as Rightel and Irancell limit websocet without SSL.

**Comment by GFW-knocker** [comment]
> Do you have any plans to support SSL in your proxy as Rightel and Irancell limit websocet without SSL.

SSL got blocked too or its bandwidth is extremely limited

but i think it can be easily possible for SSL xray to hide behind nginx
actually it dose not need proxy in the middle

keyword : nginx -> reverse proxy -> proxy_pass
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/
https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

**Comment by NadiaGarcia6** [comment]
So, it means for
