### ISSUE TITLE
TCP Module

### ISSUE THREAD

**Issue by NadiaGarcia6** [GFW-knocker/gfw_resist_http_proxy#2]
Hi

Could you please add TCP module in your proxy to support TCP traffic ...  
Sometimes mobile operators limit websocket traffic.

**Comment by GFW-knocker** [comment]
> Could you please add TCP module in your proxy to support TCP traffic ... Sometimes mobile operators limit websocket traffic.

this is not websocket

its http over TCP which is currently best protocol in iran. (1401-11)
we examine all other protocol including (quic,grpc,tls,websocket) but all them either blocked or throttled
note that sometimes whole ip get blocked in some isp and not blocked in another isp.

**Comment by NadiaGarcia6** [comment]
> > Could you please add TCP module in your proxy to support TCP traffic ... Sometimes mobile operators limit websocket traffic.
> 
> this is not websocket
> 
> its http over TCP which is currently best protocol in iran. (1401-11) we examine all other protocol including (quic,grpc,tls,websocket) but all them either blocked or throttled note that sometimes whole ip get blocked in some isp and not blocked in another isp.

I am sorry I thought it was a websocket proxy... you are completely right.
